
import React, { useState } from 'react';
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { RefreshCw, Database, AlertCircle } from 'lucide-react';
import { useToast } from "@/components/ui/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { v4 as uuidv4 } from 'uuid';

const DataPopulator: React.FC = () => {
  const [isProcessing, setIsProcessing] = useState(false);
  const [progress, setProgress] = useState(0);
  const [processedCount, setProcessedCount] = useState(0);
  const [error, setError] = useState<string | null>(null);
  const { toast } = useToast();

  // Generate a random date within the last 30 days
  const randomDate = () => {
    const now = new Date();
    const days = Math.floor(Math.random() * 30);
    const hours = Math.floor(Math.random() * 24);
    const minutes = Math.floor(Math.random() * 60);
    now.setDate(now.getDate() - days);
    now.setHours(now.getHours() - hours);
    now.setMinutes(now.getMinutes() - minutes);
    return now.toISOString();
  };

  // Generate sample visitor data
  const generateVisitorData = (count: number) => {
    const browsers = ['Chrome', 'Firefox', 'Safari', 'Edge', 'Opera'];
    const deviceTypes = ['Desktop', 'Mobile', 'Tablet'];
    const osList = ['Windows', 'macOS', 'iOS', 'Android', 'Linux'];
    const countries = [
      { code: 'US', city: 'New York', state: 'NY' },
      { code: 'US', city: 'San Francisco', state: 'CA' },
      { code: 'GB', city: 'London', state: null },
      { code: 'CA', city: 'Toronto', state: 'ON' },
      { code: 'AU', city: 'Sydney', state: 'NSW' },
    ];
    const paths = ['/', '/about', '/services', '/portfolio', '/contact', '/get-quote', '/packages', '/partners'];
    const referrers = ['https://google.com', 'https://facebook.com', 'https://twitter.com', 'https://linkedin.com', null];
    
    return Array(count).fill(null).map(() => {
      const session_id = uuidv4();
      const country = countries[Math.floor(Math.random() * countries.length)];
      return {
        session_id,
        user_agent: `Mozilla/5.0 (compatible)`,
        language: 'en-US',
        screen_width: Math.floor(Math.random() * 1000) + 800,
        screen_height: Math.floor(Math.random() * 600) + 600,
        timezone: 'America/New_York',
        referrer: referrers[Math.floor(Math.random() * referrers.length)],
        path: paths[Math.floor(Math.random() * paths.length)],
        ip_address: `192.168.${Math.floor(Math.random() * 255)}.${Math.floor(Math.random() * 255)}`,
        country_code: country.code,
        city: country.city,
        state: country.state,
        browser: browsers[Math.floor(Math.random() * browsers.length)],
        os: osList[Math.floor(Math.random() * osList.length)],
        device_type: deviceTypes[Math.floor(Math.random() * deviceTypes.length)],
        created_at: randomDate()
      };
    });
  };

  // Generate sample form submission data
  const generateFormData = (count: number) => {
    const formNames = ['contact', 'quote', 'newsletter'];
    const paths = ['/contact', '/get-quote', '/'];
    
    return Array(count).fill(null).map(() => {
      const formType = Math.floor(Math.random() * formNames.length);
      const formName = formNames[formType];
      const path = paths[formType];

      let formData: any;
      
      if (formName === 'contact') {
        formData = {
          name: `Test User ${Math.floor(Math.random() * 1000)}`,
          email: `test${Math.floor(Math.random() * 1000)}@example.com`,
          subject: `Inquiry about ${['Website', 'Mobile App', 'Design', 'Marketing'][Math.floor(Math.random() * 4)]}`,
          message: 'This is a test message generated by the data populator.'
        };
      } else if (formName === 'quote') {
        formData = {
          full_name: `Test User ${Math.floor(Math.random() * 1000)}`,
          company_name: `Company ${Math.floor(Math.random() * 100)}`,
          email: `test${Math.floor(Math.random() * 1000)}@example.com`,
          phone: `555-${Math.floor(Math.random() * 900) + 100}-${Math.floor(Math.random() * 9000) + 1000}`,
          budget: ['$1,000 - $5,000', '$5,000 - $10,000', '$10,000+'][Math.floor(Math.random() * 3)],
          service_type: ['Website Development', 'Mobile App', 'UI/UX Design', 'Branding'][Math.floor(Math.random() * 4)],
          project_description: 'This is a test project description generated by the data populator.',
          timeline: ['1-2 months', '3-6 months', '6+ months'][Math.floor(Math.random() * 3)],
          terms_accepted: true
        };
      } else {
        formData = {
          email: `test${Math.floor(Math.random() * 1000)}@example.com`
        };
      }
      
      return {
        session_id: uuidv4(),
        form_name: formName,
        form_data: formData,
        path,
        created_at: randomDate()
      };
    });
  };

  // Generate sample chat interaction data
  const generateChatData = (count: number) => {
    const questions = [
      "What services do you offer?",
      "How much does a website cost?",
      "Can you help with mobile app development?",
      "Do you offer SEO services?",
      "What's your process for starting a new project?",
      "How long does it take to build a website?",
      "Can I see some examples of your work?",
      "Do you offer maintenance plans?",
      "How can I contact your team directly?"
    ];
    
    const responses = [
      "We offer a variety of services including web development, mobile app development, UI/UX design, and branding.",
      "Website costs depend on your specific requirements. Our packages start at $5,000 for basic websites and go up from there.",
      "Yes, we specialize in both iOS and Android app development.",
      "Yes, we offer comprehensive SEO services to help improve your website's visibility.",
      "Our process begins with a discovery meeting, followed by wireframing, design, development, testing, and launch.",
      "A typical website takes 6-8 weeks to complete, but this can vary based on complexity.",
      "You can view our portfolio on our website under the 'Portfolio' section.",
      "Yes, we offer monthly maintenance plans to keep your website secure and up-to-date.",
      "You can reach us by phone at 555-123-4567 or by email at contact@example.com."
    ];
    
    // Generate 1-5 chat sessions
    const sessions = Array(Math.floor(Math.random() * 5) + 1).fill(null).map(() => uuidv4());
    
    return Array(count).fill(null).map(() => {
      const session_id = sessions[Math.floor(Math.random() * sessions.length)];
      const questionIndex = Math.floor(Math.random() * questions.length);
      
      return {
        session_id,
        user_name: Math.random() > 0.5 ? `Visitor ${Math.floor(Math.random() * 1000)}` : null,
        user_email: Math.random() > 0.7 ? `visitor${Math.floor(Math.random() * 1000)}@example.com` : null,
        message: questions[questionIndex],
        response: responses[questionIndex],
        created_at: randomDate()
      };
    });
  };

  // Populate the database with sample data
  const populateData = async () => {
    setIsProcessing(true);
    setProgress(0);
    setProcessedCount(0);
    setError(null);
    
    try {
      // Step 1: Clear existing data
      toast({
        title: "Clearing existing data",
        description: "Removing all existing analytics data...",
        variant: "default"
      });
      
      await supabase.from('visitor_tracking').delete().neq('id', '00000000-0000-0000-0000-000000000000');
      await supabase.from('form_submissions').delete().neq('id', '00000000-0000-0000-0000-000000000000');
      await supabase.from('chat_interactions').delete().neq('id', '00000000-0000-0000-0000-000000000000');
      
      setProgress(20);
      
      // Step 2: Generate and insert visitor data (100 records)
      toast({
        title: "Adding visitor data",
        description: "Generating 100 visitor records...",
        variant: "default"
      });
      
      const visitorData = generateVisitorData(100);
      
      for (let i = 0; i < visitorData.length; i += 10) {
        const batch = visitorData.slice(i, i + 10);
        await supabase.from('visitor_tracking').insert(batch);
        setProgress(20 + Math.floor((i / visitorData.length) * 30));
        setProcessedCount(i + batch.length);
        await new Promise(resolve => setTimeout(resolve, 100)); // Small delay to avoid rate limits
      }
      
      setProgress(50);
      
      // Step 3: Generate and insert form submission data (30 records)
      toast({
        title: "Adding form submission data",
        description: "Generating 30 form submission records...",
        variant: "default"
      });
      
      const formData = generateFormData(30);
      
      for (let i = 0; i < formData.length; i += 5) {
        const batch = formData.slice(i, i + 5);
        await supabase.from('form_submissions').insert(batch);
        setProgress(50 + Math.floor((i / formData.length) * 25));
        setProcessedCount(100 + i + batch.length);
        await new Promise(resolve => setTimeout(resolve, 100)); // Small delay to avoid rate limits
      }
      
      setProgress(75);
      
      // Step 4: Generate and insert chat interaction data (50 records)
      toast({
        title: "Adding chat interaction data",
        description: "Generating 50 chat interaction records...",
        variant: "default"
      });
      
      const chatData = generateChatData(50);
      
      for (let i = 0; i < chatData.length; i += 5) {
        const batch = chatData.slice(i, i + 5);
        await supabase.from('chat_interactions').insert(batch);
        setProgress(75 + Math.floor((i / chatData.length) * 25));
        setProcessedCount(130 + i + batch.length);
        await new Promise(resolve => setTimeout(resolve, 100)); // Small delay to avoid rate limits
      }
      
      setProgress(100);
      
      toast({
        title: "Data population complete",
        description: "Successfully added sample analytics data.",
        variant: "default"
      });
    } catch (err: any) {
      console.error('Error populating data:', err);
      setError(err.message || "Failed to populate analytics data");
      toast({
        title: "Error populating data",
        description: err.message || "Failed to populate analytics data",
        variant: "destructive"
      });
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <Card className="bg-gray-800/50 border-gray-700 text-white mb-6">
      <CardHeader className="pb-2">
        <CardTitle className="flex items-center gap-2">
          <Database className="h-5 w-5" />
          Analytics Data Populator
        </CardTitle>
        <CardDescription className="text-gray-400">
          Generate sample analytics data for testing and demonstration purposes
        </CardDescription>
      </CardHeader>
      <CardContent>
        {error && (
          <div className="flex items-center gap-2 text-red-400 mb-4 p-2 bg-red-900/20 rounded-md">
            <AlertCircle className="h-4 w-4" />
            <p className="text-sm">{error}</p>
          </div>
        )}
        
        <div className="space-y-4">
          {isProcessing && (
            <div className="space-y-2">
              <Progress value={progress} className="h-2" />
              <p className="text-sm text-gray-400">
                Processing {processedCount} of 180 records ({progress}% complete)
              </p>
            </div>
          )}
          
          <Button 
            onClick={populateData} 
            disabled={isProcessing}
            className="w-full"
            variant="destructive"
          >
            {isProcessing ? (
              <>
                <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
                Generating Sample Data...
              </>
            ) : (
              <>
                <Database className="h-4 w-4 mr-2" />
                Populate Analytics Data
              </>
            )}
          </Button>
          <p className="text-xs text-gray-500 text-center">
            Warning: This will clear existing analytics data and replace it with sample data
          </p>
        </div>
      </CardContent>
    </Card>
  );
};

export default DataPopulator;
