
import { v4 as uuidv4 } from 'uuid';
import { GeneratedVisitorData, GeneratedFormData, GeneratedChatData } from '@/types/generatedData';

// Generate a random date within the last 30 days
export const randomDate = (): string => {
  const now = new Date();
  const days = Math.floor(Math.random() * 30);
  const hours = Math.floor(Math.random() * 24);
  const minutes = Math.floor(Math.random() * 60);
  now.setDate(now.getDate() - days);
  now.setHours(now.getHours() - hours);
  now.setMinutes(now.getMinutes() - minutes);
  return now.toISOString();
};

// Generate sample visitor data
export const generateVisitorData = (count: number): GeneratedVisitorData[] => {
  const browsers = ['Chrome', 'Firefox', 'Safari', 'Edge', 'Opera'];
  const deviceTypes = ['Desktop', 'Mobile', 'Tablet'];
  const osList = ['Windows', 'macOS', 'iOS', 'Android', 'Linux'];
  const countries = [
    { code: 'US', city: 'New York', state: 'NY' },
    { code: 'US', city: 'San Francisco', state: 'CA' },
    { code: 'GB', city: 'London', state: null },
    { code: 'CA', city: 'Toronto', state: 'ON' },
    { code: 'AU', city: 'Sydney', state: 'NSW' },
  ];
  const paths = ['/', '/about', '/services', '/portfolio', '/contact', '/get-quote', '/packages', '/partners'];
  const referrers = ['https://google.com', 'https://facebook.com', 'https://twitter.com', 'https://linkedin.com', null];
  
  return Array(count).fill(null).map(() => {
    const session_id = uuidv4();
    const country = countries[Math.floor(Math.random() * countries.length)];
    return {
      session_id,
      user_agent: `Mozilla/5.0 (compatible)`,
      language: 'en-US',
      screen_width: Math.floor(Math.random() * 1000) + 800,
      screen_height: Math.floor(Math.random() * 600) + 600,
      timezone: 'America/New_York',
      referrer: referrers[Math.floor(Math.random() * referrers.length)],
      path: paths[Math.floor(Math.random() * paths.length)],
      ip_address: `192.168.${Math.floor(Math.random() * 255)}.${Math.floor(Math.random() * 255)}`,
      country_code: country.code,
      city: country.city,
      state: country.state,
      browser: browsers[Math.floor(Math.random() * browsers.length)],
      os: osList[Math.floor(Math.random() * osList.length)],
      device_type: deviceTypes[Math.floor(Math.random() * deviceTypes.length)],
      created_at: randomDate()
    };
  });
};

// Generate sample form submission data
export const generateFormData = (count: number): GeneratedFormData[] => {
  const formNames = ['contact', 'quote', 'newsletter'];
  const paths = ['/contact', '/get-quote', '/'];
  
  return Array(count).fill(null).map(() => {
    const formType = Math.floor(Math.random() * formNames.length);
    const formName = formNames[formType];
    const path = paths[formType];

    let formData: any;
    
    if (formName === 'contact') {
      formData = {
        name: `Test User ${Math.floor(Math.random() * 1000)}`,
        email: `test${Math.floor(Math.random() * 1000)}@example.com`,
        subject: `Inquiry about ${['Website', 'Mobile App', 'Design', 'Marketing'][Math.floor(Math.random() * 4)]}`,
        message: 'This is a test message generated by the data populator.'
      };
    } else if (formName === 'quote') {
      formData = {
        full_name: `Test User ${Math.floor(Math.random() * 1000)}`,
        company_name: `Company ${Math.floor(Math.random() * 100)}`,
        email: `test${Math.floor(Math.random() * 1000)}@example.com`,
        phone: `555-${Math.floor(Math.random() * 900) + 100}-${Math.floor(Math.random() * 9000) + 1000}`,
        budget: ['$1,000 - $5,000', '$5,000 - $10,000', '$10,000+'][Math.floor(Math.random() * 3)],
        service_type: ['Website Development', 'Mobile App', 'UI/UX Design', 'Branding'][Math.floor(Math.random() * 4)],
        project_description: 'This is a test project description generated by the data populator.',
        timeline: ['1-2 months', '3-6 months', '6+ months'][Math.floor(Math.random() * 3)],
        terms_accepted: true
      };
    } else {
      formData = {
        email: `test${Math.floor(Math.random() * 1000)}@example.com`
      };
    }
    
    return {
      session_id: uuidv4(),
      form_name: formName,
      form_data: formData,
      path,
      created_at: randomDate()
    };
  });
};

// Generate sample chat interaction data
export const generateChatData = (count: number): GeneratedChatData[] => {
  const questions = [
    "What services do you offer?",
    "How much does a website cost?",
    "Can you help with mobile app development?",
    "Do you offer SEO services?",
    "What's your process for starting a new project?",
    "How long does it take to build a website?",
    "Can I see some examples of your work?",
    "Do you offer maintenance plans?",
    "How can I contact your team directly?"
  ];
  
  const responses = [
    "We offer a variety of services including web development, mobile app development, UI/UX design, and branding.",
    "Website costs depend on your specific requirements. Our packages start at $5,000 for basic websites and go up from there.",
    "Yes, we specialize in both iOS and Android app development.",
    "Yes, we offer comprehensive SEO services to help improve your website's visibility.",
    "Our process begins with a discovery meeting, followed by wireframing, design, development, testing, and launch.",
    "A typical website takes 6-8 weeks to complete, but this can vary based on complexity.",
    "You can view our portfolio on our website under the 'Portfolio' section.",
    "Yes, we offer monthly maintenance plans to keep your website secure and up-to-date.",
    "You can reach us by phone at 555-123-4567 or by email at contact@example.com."
  ];
  
  // Generate 1-5 chat sessions
  const sessions = Array(Math.floor(Math.random() * 5) + 1).fill(null).map(() => uuidv4());
  
  return Array(count).fill(null).map(() => {
    const session_id = sessions[Math.floor(Math.random() * sessions.length)];
    const questionIndex = Math.floor(Math.random() * questions.length);
    
    return {
      session_id,
      user_name: Math.random() > 0.5 ? `Visitor ${Math.floor(Math.random() * 1000)}` : null,
      user_email: Math.random() > 0.7 ? `visitor${Math.floor(Math.random() * 1000)}@example.com` : null,
      message: questions[questionIndex],
      response: responses[questionIndex],
      created_at: randomDate()
    };
  });
};
