// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcyhodvjrdcaqtlreulu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjeWhvZHZqcmRjYXF0bHJldWx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NjAwNjMsImV4cCI6MjA2MzAzNjA2M30.0eXBn13wmy-PAa9my9sDMso5yTq_90NVfrru26EyD_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);