// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://strixttogzthapdhuczm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0cml4dHRvZ3p0aGFwZGh1Y3ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1OTkyNjIsImV4cCI6MjA2MzE3NTI2Mn0.bhSZ6QY907hrVEK9fPCKHVDYI-6BKgLmi36mMOVxTxs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);